### ISSUE TITLE
Translating the Blog

### ISSUE THREAD

**Issue by carburo** [reactjs/es.react.dev#201]
Blog posts reflect a moment in time and they are not continually being updated as the docs. Also, many blog posts are simple announcements that have little value after some time.

🚨 **We should favor here latest posts and those containing additional documentation/tips that could serve as a complement to the docs.** 🚨

## For New Translators
Please check out the notes in the general translation issue #4

## Progress

- [ ] 2022-03-29-react-v18.md
- [ ] 2022-03-08-react-18-upgrade-guide.md @iMartinDav
- [ ] 2021-12-17-react-conf-2021-recap.md
- [x] 2021-06-08-the-plan-for-react-18.md
- [x] 2020-12-21-data-fetching-with-react-server-components.md @pedabraham
- [ ] 2020-10-20-react-v17.md ~@FranciscoImanolSuarez #410~
- [x] 2020-09-22-introducing-the-new-jsx-transform.md @MigueMartelo #396 
- [ ] 2020-08-10-react-v17-rc.md
- [ ] 2020-02-26-react-v16.13.0.md
- [ ] 2019-10-22-react-release-channels.md
- [ ] 2019-11-06-building-great-user-experiences-with-concurrent-mode-and-suspense.md
- [x] 2019-08-15-new-react-devtools.md @elyalvarado #297 
- [x] 2019-08-08-react-v16.9.0.md @elyalvarado #304
- [x] 2019-02-23-is-react-translated-yet.md @carburo #199 
- [ ] 2019-02-06-react-v16.8.0.md
- [x] 2018-12-19-react-v-16-7.md @alejandronanez (#317)
- [ ] 2018-11-27-react-16-roadmap.md
- [x] 2018-11-13-react-conf-recap.md @arche4 #404 
- [ ] 2018-10-23-react-v-16-6.md
- [ ] 2018-10-01-create-react-app-v2.md
- [ ] 2018-09-10-introducing-the-react-profiler.md
- [ ] 2018-08-01-react-v-16-4-2.md
- [x] 2018-06-07-you-probably-dont-need-derived-state.md @carburo #231 
- [ ] 2018-05-23-react-v-16-4.md
- [ ] 2018-03-29-react-v-16-3.md
- [ ] 2018-03-27-update-on-async-rendering.md
- [ ] 2018-03-01-sneak-peek-beyond-react-16.md
- [ ] 2017-12-15-improving-the-repository-infrastructure.md
- [ ] 2017-12-07-introducing-the-react-rfc-process.md
- [ ] 2017-11-28-react-v16.2.0-fragment-support.md
- [ ] 2017-09-26-react-v16.0.md
- [ ] 2017-09-25-react-v15.6.2.md
- [ ] 2017-09-08-dom-attributes-in-react-16.md
- [ ] 2017-07-26-error-handling-in-react-16.md
- [ ] 2017-06-13-react-v15.6.0.md
- [ ] 2017-05-18-whats-new-in-create-react-app.md @joelcmk
- [ ] 2017-04-07-react-v15.5.0.md
- [ ] 2016-11-16-react-v15.4.0.md
- [ ] 2016-09-28-our-first-50000-stars.md
- [ ] 2016-08-05-relay-state-of-the-state.md
- [ ] 2016-07-22-create-apps-with-no-configuration.md
- [ ] 2016-07-13-mixins-considered-harmful.md
- [ ] 2016-07-11-introducing-reacts-error-code-system.md
- [ ] 2016-04-08-react-v15.0.1.md
- [ ] 2016-04-07-react-v15.md
- [ ] 2016-03-29-react-v0.14.8.md
- [ ] 2016-03-16-react-v15-rc2.md
- [ ] 2016-03-07-react-v15-rc1.md
- [ ] 2016-02-19-new-versioning-scheme.md
- [ ] 2016-01-12-discontinuing-ie8-support.md
- [ ] 2016-01-08-A-implies-B-does-not-imply-B-implies-A.md
- [ ] 2015-12-29-react-v0.14.4.md
- [ ] 2015-12-18-react-components-elements-and-instances.md
- [ ] 2015-12-16-ismounted-antipattern.md
- [ ] 2015-12-04-react-js-conf-2016-diversity-scholarship.md
- [ ] 2015-11-18-react-v0.14.3.md
- [ ] 2015-11-02-react-v0.14.2.md
- [ ] 2015-10-28-react-v0.14.1.md
- [ ] 2015-10-19-reactiflux-is-moving-to-discord.md
- [ ] 2015-10-07-react-v0.14.md
- [ ] 2015-10-01-react-render-and-top-level-api.md
- [ ] 2015-09-14-community-roundup-27.md
- [ ] 2015-09-10-react-v0.14-rc1.md
- [ ] 2015-09-02-new-react-developer-tools.md
- [ ] 2015-08-13-reacteurope-roundup.md
- [ ] 2015-08-11-relay-technical-preview.md
- [ ] 2015-08-03-new-react-devtools-beta.md
- [ ] 2015-07-03-react-v0.14-beta-1.md
- [ ] 2015-06-12-deprecating-jstransform-and-react-tools.md
- [ ] 2015-05-22-react-native-release-process.md
- [ ] 2015-05-08-react-v0.13.3.md
- [ ] 2015-05-01-graphql-introduction.md
- [ ] 2015-04-18-react-v0.13.2.md
- [ ] 2015-04-17-react-native-v0.4.md
- [ ] 2015-03-30-community-roundup-26.md
- [ ] 2015-03-26-introducing-react-native.md
- [ ] 2015-03-19-building-the-facebook-news-feed-with-relay.md
- [ ] 2015-03-16-react-v0.13.1.md
- [ ] 2015-03-10-react-v0.13.md
- [ ] 2015-03-04-community-roundup-25.md
- [ ] 2015-03-03-react-v0.13-rc2.md
- [ ] 2015-02-24-streamlining-react-elements.md
- [ ] 2015-02-24-react-v0.13-rc1.md
- [ ] 2015-02-20-introducing-relay-and-graphql.md
- [ ] 2015-02-18-react-conf-roundup-2015.md
- [ ] 2015-01-27-react-v0.13.0-beta-1.md
- [ ] 2014-12-19-react-js-conf-diversity-scholarship.md
- [ ] 2014-12-18-react-v0.12.2.md
- [ ] 2014-11-25-community-roundup-24.md
- [ ] 2014-11-24-react-js-conf-updates.md
- [ ] 2014-10-28-react-v0.12.md
- [ ] 2014-10-27-react-js-conf.md
- [ ] 2014-10-17-community-roundup-23.md
- [ ] 2014-10-16-react-v0.12-rc1.md
- [ ] 2014-10-14-introducing-react-elements.md
- [ ] 2014-09-24-testing-flux-applications.md
- [ ] 2014-09-16-react-v0.11.2.md
- [ ] 2014-09-12-community-round-up-22.md
- [x] 2014-09-03-introducing-the-jsx-specification.md @FLiotta 
- [ ] 2014-08-03-community-roundup-21.md
- [ ] 2014-07-30-flux-actions-and-the-dispatcher.md
- [ ] 2014-07-28-community-roundup-20.md
- [ ] 2014-07-25-react-v0.11.1.md
- [ ] 2014-07-17-react-v0.11.md
- [ ] 2014-07-13-react-v0.11-rc1.md
- [ ] 2014-06-27-community-roundup-19.md
- [ ] 2014-05-29-one-year-of-open-source-react.md
- [ ] 2014-05-06-flux.md
- [ ] 2014-04-04-reactnet.md
- [ ] 2014-03-28-the-road-to-1.0.md
- [ ] 2014-03-21-react-v0.10.md
- [ ] 2014-03-19-react-v0.10-rc1.md
- [ ] 2014-03-14-community-roundup-18.md
- [ ] 2014-02-24-community-roundup-17.md
- [ ] 2014-02-20-react-v0.9.md
- [ ] 2014-02-16-react-v0.9-rc1.md
- [ ] 2014-02-15-community-roundup-16.md
- [ ] 2014-02-05-community-roundup-15.md
- [ ] 2014-01-06-community-roundup-14.md
- [ ] 2014-01-02-react-chrome-developer-tools.md
- [ ] 2013-12-30-community-roundup-13.md
- [ ] 2013-12-23-community-roundup-12.md
- [ ] 2013-12-19-react-v0.8.0.md
- [ ] 2013-12-18-react-v0.5.2-v0.4.2.md
- [ ] 2013-11-18-community-roundup-11.md
- [ ] 2013-11-06-community-roundup-10.md
- [ ] 2013-10-3-community-roundup-9.md
- [ ] 2013-10-29-react-v0-5-1.md
- [ ] 2013-10-16-react-v0.5.0.md
- [ ] 2013-09-24-community-roundup-8.md
- [ ] 2013-08-26-community-roundup-7.md
- [ ] 2013-08-19-use-react-and-jsx-in-python-applications.md
- [ ] 2013-08-05-community-roundup-6.md
- [ ] 2013-07-30-use-react-and-jsx-in-ruby-on-rails.md
- [ ] 2013-07-26-react-v0-4-1.md
- [ ] 2013-07-23-community-roundup-5.md
- [ ] 2013-07-17-react-v0-4-0.md
- [ ] 2013-07-11-react-v0-4-prop-validation-and-default-values.md
- [ ] 2013-07-03-community-roundup-4.md
- [ ] 2013-07-02-react-v0-4-autobind-by-default.md
- [ ] 2013-06-27-community-roundup-3.md
- [x] 2013-06-21-react-v0-3-3.md @FLiotta 
- [ ] 2013-06-19-community-roundup-2.md
- [x] 2013-06-12-community-roundup.md @mishelashala #203 
- [x] 2013-06-05-why-react.md @mishelashala #190 
- [x] 2013-06-02-jsfiddle-integration.md @mishelashala #187

**Comment by mishelashala** [comment]
Hi, I'm working on the translation for `2013-06-12-community-roundup.md` :)

**Comment by AlxSavage** [comment]
Hello! Working on translating `2019-02-06-react-v16.8.0.md` 👌

**Comment by carburo** [comment]
Welcome @AlxSavage! I assigned it to you. Thank you!

**Comment by elyalvarado** [comment]
Hello! I'm just finished translating the "Introducing New React DevTools" blog article from 2019-08-15, which is the latest article and is not in the list. @carburo @alejandronanez

**Comment by elyalvarado** [comment]
I'm also working on translating `2019-08-08-react-v16.9.0.md` so that the last 3 posts in the blog get translated

**Comment by gndx** [comment]
Hi, i'm working on translating  `2018-11-13-react-conf-recap.md`

**Comment by carburo** [comment]
Hi, @gndx. You got it!

**Comment by condef5** [comment]
Hi, I would like to translate [this article](https://es.reactjs.org/blog/2020/02/26/react-v16.13.0.html) :)

**Comment by carburo** [comment]
Hi @condef5! Sure, go for it!

**Comment by aroundarmor** [comment]
Hi I want to translate react-release-channels.md,
can you assign it to me?

**Comment by aroundarmor** [comment]
content/docs/release-channels.md can you confirm the document location that needs to be translated?

**Comment by alejandronanez** [comment]
@aroundarmor, I just assigned it to you. 👍

**Comment by aroundarmor** [comment]
Hello @alejandronanez , Thanks for assigning me this.
I've raised a PR. Please review it.

**Comment by alejandronanez** [comment]
> Hello @alejandronanez , Thanks for assigning me this.
> 
> I've raised a PR. Please review it.

@aroundarmor Thanks!!!

It will help us a lot that you link the PR in your comment next time. I reviewed your PR but still needs a lot of work, let's move the conversation over there.

**Comment by FLiotta** [comment]
Hello, may i translate 2014-09-03-introducing-the-jsx-specification.md? ^^

**Comment by elyalvarado** [comment]
@alejandronanez, @carburo I'll like to take `2019-11-06-building-great-user-experiences-with-concurrent-mode-and-suspense.md`

**Comment by alejandronanez** [comment]
Go for it @elyalvarado!

**Comment by alejandronanez** [comment]
> Hello, may i translate 2014-09-03-introducing-the-jsx-specification.md? ^^

@FLiotta go for it!

**Comment by MigueMartelo** [comment]
Hi @alejandronanez , @carburo I'll be working in `2020-09-22-introducing-the-new-jsx-transform.md`

**Comment by apenab** [comment]
Hacktoberfest tag for this issue plz

#hacktoberfest

**Comment by ktowen** [comment]
I would like to translate `2015-12-04-react-js-conf-2016-diversity-scholarship.md`

**Comment by apenab** [comment]
I would like to translate `2019-02-06-react-v16.8.0.md`

**Comment by arche4** [comment]
Hi guys, I would like to translate 2018-11-13-react-conf-recap.md

**Comment by arche4** [comment]
Hi guys, I would like to translate  2018-10-01-create-react-app-v2.md

**Comment by carburo** [comment]
Hi @arche4! I assigned you "React Conf Recap." We usually assign one at a time, so you can claim another one once you have an open PR. Thanks!

**Comment by FLiotta** [comment]
Hello, may i take 2013-06-21-react-v0-3-3.md?

**Comment by carburo** [comment]
Hi @FLiotta! Yes, go for it!

**Comment by pedabraham** [comment]
Hi, I would like to translate `2020-12-21-data-fetching-with-react-server-components.md`

**Comment by alejandronanez** [comment]
> Hi, I would like to translate `2020-12-21-data-fetching-with-react-server-components.md`

Go for it @pedabraham 🙌

**Comment by pedabraham** [comment]
Hi @carburo, I sent the PR #426 with the translation of `2020-12-21-data-fetching-with-react-server-components.md`

**Comment by cristianbgp** [comment]
Hi @carburo I have the translation of the new blog post about React 18 `2021-06-08-the-plan-for-react-18.md` on #461

**Comment by Carababusha** [comment]
Hi @carburo, @alejandronanez and everybody. I can help with translating some of this as my first issue, which of the files that haven't been translated yet would you need translated first?

**Comment by Carababusha** [comment]
¡Hola @carburo! Genial. Si viene bien, puedo ponerme manos a la obra con el artículo del blog 2020-12-21-data-fetching-with-react-server-components.md, que es el más reciente que queda por traducir.

**Comment by pedabraham** [comment]
Hola @Carababusha tengo un pr abierto (#426 ) con esa traducción, tal vez la podrías revisar y notar algún error que haya tenido.

**Comment by Carababusha** [comment]
¡Hola @pedabraham! Pues si sirve de ayuda me pongo con ello ☺️

**Comment by Carababusha** [comment]
> Hola @Carababusha tengo un pr abierto (#426 ) con esa traducción, tal vez la podrías revisar y notar algún error que haya tenido.

¡Hola de nuevo @pedabraham! Le he echado un vistazo a tu PR y he dejado algunos comentarios con sugerencias. ¡Espero que te parezcan útiles!

**Comment by joelcmk** [comment]
Hi, can I translate 2017-05-18-whats-new-in-create-react-app.md ?

**Comment by carburo** [comment]
@iMartinDav ¿Aún estás interesado en traducir la página? Disculpa la respuesta tardía, pero habíamos detenido el proceso de traducción en espera a terminar la migración al nuevo sitio.

**Comment by iMartinDav** [comment]
> 

¿Todavía puedo participar en la traducción?
